#103 install xml2rfc deps
metanorma/metanorma-ietf pull request #104
Opened 2020-10-11 20:55 UTC by CAMOBAP

- #103

2020-10-13 09:42 UTC, CAMOBAP commented
As I understand the validation scheme was changed, investigation in progress

2020-10-13 18:10 UTC, CAMOBAP commented
@opoudjis I'm not 100% sure about removing this class variable could you please review

2020-10-15 09:27 UTC, opoudjis commented
The `@done_rfc` is there to ensure that the File.exists has been recompiled; if it's been sitting around from an earlier compilation, it's not valid. Yes, please keep both.

2020-10-15 09:28 UTC, opoudjis requested changes
Please use both `@done_rfc` and File.exists

2020-10-15 09:56 UTC, CAMOBAP commented
@opoudjis done

2020-10-20 19:42 UTC, CAMOBAP commented
@ronaldtse @opoudjis could you please review again

2020-10-20 23:15 UTC, ronaldtse approved these changes

2020-10-20 23:15 UTC, ronaldtse commented on lib/metanorma/ietf/processor.rb
> +            when :txt then "--text"
You can also write something like:

```ruby
outext, outflag = case format
  when :txt then [".txt", "--txt"]
  when :pdf then [".pdf", "--pdf"]
  when :html then [".html", "--html"]
end
```

2020-10-21 12:58 UTC, merged